services:
  unimusic-server:
    build:
      context: ./unimusic-server
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    networks:
      - internal_network

  playlist-server:
    build:
      context: ./playlist-server
    ports:
      - "8081:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - internal_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8082:80"
    networks:
      - internal_network

volumes:
  pgdata:


networks:
  internal_network:
    driver: bridge
