POST http://localhost:8080/usuarios/registrar
Content-Type: application/json

{
    "nomeUsuario": "sergiobrito",
    "email": "sergiowilson1999@gmail.com",
    "senha": "123"
}

GET http://localhost:8080/musicas/stream/01%20Double-F%20the%20King%20-%20Missing%20My%20Babygirl.mp3