package br.unibh.sdm.unimusic_playlist.entidades;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "playlists")
public class Playlist {
    private String id;
    private String nome;
    private String usuarioId;
    private List<String> musicasIds;

    public Playlist() {}

    public Playlist(String nome, String usuarioId, List<String> musicasIds) {
        this.nome = nome;
        this.usuarioId = usuarioId;
        this.musicasIds = musicasIds;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
    @DynamoDBAttribute
    public String getNome() {
        return nome;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }
    @DynamoDBAttribute
    public String getUsuarioId() {
        return usuarioId;
    }
    public void setUsuarioId(String usuario) {
        this.usuarioId = usuario;
    }
    @DynamoDBAttribute
    public List<String> getMusicasIds() {
        return musicasIds;
    }
    public void setMusicasIds(List<String> musicas) {
        this.musicasIds = musicas;
    }
}

